#!/bin/sh

rm -f vim/ftdetect/S1000D.vim

for issue in S1000D_41 S1000D_42
do
	for f in schemas/$issue/*
	do
		base=$(basename "$f")
		ns="${issue}_$(basename "$f" .xsd)"
		out="vim/autoload/xml/${ns}.vim"

		echo "Converting ${f} to ${out}..."

		xsltproc -stringparam namespace "$ns" xsd2omni.xsl "$f" > "$out"

		case "$issue" in
			S1000D_41) urliss="S1000D_4-1" ;;
			S1000D_42) urliss="S1000D_4-2" ;;
		esac

		echo "au BufRead *.[Xx][Mm][Ll] if search('noNamespaceSchemaLocation=\"http://www.s1000d.org/${urliss}/xml_schema_flat/${base}\"','n') | call xmlcomplete#CreateConnection('${ns}') | endif" >> vim/ftdetect/S1000D.vim
	done
done
